export default function Terms() {
  return (
    <div style={{ maxWidth: 680, margin: "0 auto", padding: "48px 24px 80px" }}>
      <a href="/" style={{ display: "inline-flex", alignItems: "center", gap: 8, textDecoration: "none", marginBottom: 32 }}>
        <div style={{ width: 28, height: 28, borderRadius: 7, background: "var(--terra, #C4652A)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 13, fontWeight: 700, color: "#fff" }}>N</div>
        <span style={{ fontFamily: "'Fraunces', serif", fontSize: 17, fontWeight: 700, color: "var(--text, #2C2418)" }}>NoteBack</span>
      </a>

      <h1 style={{ fontFamily: "'Fraunces', serif", fontSize: 32, fontWeight: 900, marginBottom: 8, color: "var(--text, #2C2418)" }}>Terms of Service</h1>
      <p style={{ fontSize: 13, color: "var(--dim, #8C7B6B)", marginBottom: 32 }}>Last updated: March 15, 2026</p>

      {[
        { t: "Service description", b: "NoteBack is an AI-powered tool that generates professional responses to customer reviews. The service is provided as-is. Generated responses are suggestions — you are responsible for reviewing and editing responses before posting them publicly." },
        { t: "Free tier", b: "The free tier provides up to 3 AI-generated review responses per day at no cost. No account or signup is required. NoteBack reserves the right to modify the free tier limits at any time." },
        { t: "Pro subscription", b: "NoteBack Pro provides unlimited review responses for $19/month or $149/year. Subscriptions are billed through Stripe. You may cancel at any time through the Manage Subscription link or by contacting support@noteback.co. Cancellation takes effect at the end of the current billing period." },
        { t: "Refunds", b: "If you are unsatisfied with NoteBack Pro, contact support@noteback.co within 14 days of your first payment for a full refund. After 14 days, no refunds are provided, but you may cancel at any time to prevent future charges." },
        { t: "Acceptable use", b: "You may not use NoteBack to generate responses that are defamatory, fraudulent, misleading, or illegal. You may not use automated scripts or bots to access the service beyond the intended rate limits. You are solely responsible for the content you post on review platforms using NoteBack-generated responses." },
        { t: "AI-generated content", b: "Responses generated by NoteBack are AI-created suggestions. They should be reviewed before posting. NoteBack does not guarantee the accuracy, appropriateness, or effectiveness of any generated response. You assume full responsibility for any response you choose to post." },
        { t: "Limitation of liability", b: "NoteBack is provided as-is without warranties of any kind. NoteBack shall not be liable for any damages arising from the use of the service, including but not limited to loss of business, reputation damage, or any consequences of posting AI-generated responses." },
        { t: "Changes to terms", b: "NoteBack may update these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms." },
        { t: "Contact", b: "For questions about these terms, email support@noteback.co." },
      ].map((s, i) => (
        <div key={i} style={{ marginBottom: 24 }}>
          <h2 style={{ fontFamily: "'Fraunces', serif", fontSize: 18, fontWeight: 700, marginBottom: 6, color: "var(--text, #2C2418)" }}>{s.t}</h2>
          <p style={{ fontSize: 14, color: "var(--dim, #8C7B6B)", lineHeight: 1.7 }}>{s.b}</p>
        </div>
      ))}

      <div style={{ borderTop: "1px solid var(--border, #E8DDD0)", paddingTop: 24, marginTop: 32 }}>
        <a href="/" style={{ fontSize: 13, color: "var(--terra, #C4652A)", textDecoration: "none", fontWeight: 600 }}>← Back to NoteBack</a>
      </div>
    </div>
  );
}
